---
- name: Check if certificate already exists.
  stat:
    path: /etc/letsencrypt/live/{{ nginx_loadbalancer_domain | first | replace('*.', '') }}/cert.pem
  register: __letsencrypt_cert

- name: Ensure pre and post hook folders exist.
  file:
    path: /etc/letsencrypt/renewal-hooks/{{ item }}
    state: directory
    mode: 0755
    owner: root
    group: root
  loop:
    - pre
    - post

- name: Generate new certificate if one doesn't exist.
  command: certbot --non-interactive --nginx --agree-tos --redirect --email '{{ nginx_loadbalancer_admin_email }}'  --domains "{{ nginx_loadbalancer_domain }}"
  when: not __letsencrypt_cert.stat.exists

  