---
# Parameters used when creating new Certbot certs.
nginx_loadbalancer_admin_email: bexruzturobjonov0955@gmail.com
nginx_loadbalancer_certbot_certificate_presence: yes

  
nginx_loadbalancer_domain: vaultb.bexruzdev.uz
nginx_loadbalancer_upstream: vaultb.bexruzdev.uz
nginx_loadbalancer_client_max_body_size: 100M
#*  vault cluster IPs
nginx_loadbalancer_host1: 135.181.46.196 #ip
nginx_loadbalancer_host2: 37.27.40.125 #ip  
nginx_loadbalancer_host3: 65.108.148.117 #ip
nginx_loadbalancer_port:
nginx_loadbalancer_renew: true