---
# defaults file for external_bankvault

external_bankvault_address: "https://domain.uz" #your vault cluster address
external_bankvault_token: "hvs.token" # Your vault Token 
external_bankvault_kubeconfig_vault_path: # path to kube config file in vault


external_bankvault_loop:
  - external_bankvault_namespace: "testnamespace1" #name for k8s namespace
    external_bankvault_role_name: "testrole1" #new name for vault role
    external_bankvault_secret_path: "k8s/testlab1" #secret path. Dont begin with secret engine

  - external_bankvault_namespace: "testnamespace2"
    external_bankvault_role_name: "testrole2"
    external_bankvault_secret_path: "k8s/testlab2"
    





