---
# defaults file for vault_injector

vault_injector_address: "" #your vault cluster address
vault_injector_token: "" # Your vault Token 
vault_injector_kubeconfig_vault_path: # path to kube config file in vault
vault_injector_project: ""  # your project name