---
# defaults file for vault_injector

vault_injector_address: "http://18.212.236.56:8200" #your vault cluster address
vault_injector_token: "hvs.DpMVigg8GjQxhEdPFAYZpwz7" # Your vault Token 
vault_injector_project: awx1   # your project name