---
# defaults file for vault_injector

vault_injector_address: "{{ lookup('env', 'VAULT_ADDR') }}" #your vault cluster address
vault_injector_token: "{{  __login_data.login.auth.client_token }}" # Your vault Token 
vault_injector_kubeconfig_vault_path: # path to kube config file in vault
vault_injector_project: ""  # your project name

vault_injector_loop:
  - vault_injector_namespace: "" #name for k8s namespace
    vault_injector_role_name: "" #new name for vault role
    vault_injector_secret_path: "" #secret path. Dont begin with secret engine
  - vault_injector_namespace: ""
    vault_injector_role_name: ""
    vault_injector_secret_path: ""